apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
      - name: kibana
        image: upmcenterprises/kibana:5.3.1
        imagePullPolicy: Always
        env:
        - name: ELASTICSEARCH_URL
          value: https://elasticsearch-example-es-cluster.operator:9200
        - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
          value: /elasticsearch/config/certs/ca.pem
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        volumeMounts:
          - mountPath: /elasticsearch/config/certs
            name: es-certs-example-es-cluster
      volumes: 
        - name: es-certs-example-es-cluster
          secret:
            secretName: es-certs-example-es-cluster